// SIGNUP ACTION TYPES
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";

// USER AUTH ACTION TYPES
export const AUTH_USER = "AUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
