// AUTH ACTION TYPES
export const AUTH_START = "AUTH_START";
export const AUTH_END = "AUTH_END";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

// EMAIL VERIFICATION ACTION TYPES
export const VERIFY_EMAIL_START = "VERIFY_EMAIL_START"
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS"
export const VERIFY_EMAIL_FAIL = "VERIFY_EMAIL_FAIL"

// FRONT END ACTIONS
export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

// TODO ACTIONS
export const ADD_ROOM_START = 'ADD_ROOM_START';
export const ADD_ROOM_SUCCESS = 'ADD_ROOM_SUCCESS';
export const ADD_ROOM_FAIL = 'ADD_ROOM_FAIL';
